---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: install packages
      package:
        name: 
          - firefox
          - alacritty
          - ranger
          - zsh
          - sxhkd
          - polybar
          - nitrogen
          - compton
          - ttf-dejavu
          - xorg-server
          - xorg-xinit
          - rofi
          - stow
          - neofetch
          - neovim

    - name: Clone Dotfiles
      ansible.builtin.git:
        repo: 'https://github.com/CuriousTea/.dotfiles'
        dest: /home/ {{ username }}/

