---
- hosts: localhost
  connection: local
  become: true
  vars:
    username: teclis

  tasks:
    - name: install packages
      package:
        name: 
          - i3-gaps
          - firefox
          - alacritty
          - ranger
          - zsh
          - sxhkd
          - polybar
          - nitrogen
          - compton
          - ttf-dejavu
          - xorg-server
          - xorg-xinit
          - rofi
          - stow
          - neofetch
          - neovim

    - name: Clone Dotfiles
      ansible.builtin.git:
        repo: 'https://github.com/CuriousTea/.dotfiles'
        dest: /home/{{ username }}/.dotfiles
        
    - name: Stow a directory
      ansible.builtin.shell: |
        stow */
      args:
         chdir: "/home/{{ username }}/.dotfiles"
         
    - name: create a symbolic .zshrc
      ansible.builtin.shell: |
        ln -s /home/{{ username }}/.config/zsh/.zshrc /home/{{ username }}/.zshrc 
      args:
        chdir: "/home/{{ username }}"
        
    - name: download yay package
      ansible.builtin.git:
        repo: 'https://aur.archlinux.org/yay-git.git'
        dest: /opt/yay-git
        
    - name: ensure yay does not have root perms
      ansible.builtin.shell: |
        sudo chown -R {{ username }}:{{ username }} ./yay-git
      args:
         chdir: "/opt"

    - name: ensure yay does not have root perms
      ansible.builtin.shell: |
        sudo makepkg -si
      args:
         chdir: "/opt/yay-git"
        
   
