---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: install packages
      package:
        name: 
          - git
          - firefox
          - alacritty
          - ranger
          - zsh
          - sxhkd
          - polybar
          - nitrogen
          - compton
          - ttf-dejavu
          - xorg-server
          - xorg-xinit
          - rofi
          - stow
    - name: copy a file test
      copy:
        src: files/testfile.txt
        dest: ~/diditwork.txt
        owner: teclis
        group: teclis

