---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: install packages
      package:
        name: 
          - git
          - firefox
          - alacritty
          - ranger
          - zsh
          - szhkd
          - polybar
          - nitrogen
          - compton
          - ttf-dejavu
          - xorg-server
          - xorg-xinit

