---
- hosts: localhost
  connection: local
  become: true
  vars:
    username: teclis

  tasks:
    - name: install packages
      package:
        name: 
          - i3-gaps
          - firefox
          - alacritty
          - ranger
          - zsh
          - sxhkd
          - polybar
          - nitrogen
          - compton
          - ttf-dejavu
          - xorg-server
          - xorg-xinit
          - rofi
          - stow
          - neofetch
          - neovim

    - name: Clone Dotfiles
      ansible.builtin.git:
        repo: 'https://github.com/CuriousTea/.dotfiles'
        dest: /home/{{ username }}/.dotfiles
        
    - name: Stow a directory
      ansible.builtin.shell: |
        stow */
      args:
         chdir: "/home/{{ username }}/.dotfiles"
         
    - name: create a symbolic .zshrc
      ansible.builtin.shell: |
        ln -s ~/.config/zsh/.zshrc ~/.zshrc 
      args:
        chdir: "/home/{{ username }}"
        
    - name: change default shell 
      ansible.builtin.shell: |
        chsh -s /bin/zsh

